name: publish

permissions:
  id-token: write

on:
  release:
    types: [published]
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 1fd5e3779d65d43134eddebac01e35f0ea3c0ebb

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Generate source archive
        run: npm run archive
        env:
          VERSION: 0.6.0

      - name: Upload source archive
        uses: actions/upload-artifact@v4
        with:
          name: codecov-browser-extension-0.6.0.tar.gz
          path: codecov-browser-extension-0.6.0.tar.gz

      - name: Install dependencies
        run: npm install

      - name: Build Chrome extension
        run: npm run build
        env:
          VERSION: 0.6.0

      - name: Upload built Chrome extension
        uses: actions/upload-artifact@v4
        with:
          name: codecov-chrome-0.6.0
          path: ./dist/

      # - name: Publish to Chrome
      #   working-directory: dist
      #   run: npx chrome-webstore-upload-cli@3
      #   env:
      #     EXTENSION_ID: "gedikamndpbemklijjkncpnolildpbgo"
      #     CLIENT_ID: ${{ secrets.GOOGLE_WEB_STORE_CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.GOOGLE_WEB_STORE_CLIENT_SECRET }}
      #     REFRESH_TOKEN: ${{ secrets.GOOGLE_WEB_STORE_REFRESH_TOKEN }}

      - name: Clean dist
        run: rm -r dist

      - name: Build Firefox extension
        run: npm run build:firefox
        env:
          VERSION: 0.6.0

      - name: Upload built Firefox extension
        uses: actions/upload-artifact@v4
        with:
          name: codecov-firefox-0.6.0
          path: ./dist/

      # - name: Publish to Firefox
      #   working-directory: dist
      #   run: npx web-ext sign
      #   env:
      #     WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_JWT_ISSUER }}
      #     WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_JWT_SECRET }}
      #     WEB_EXT_CHANNEL: listed
      #     WEB_EXT_UPLOAD_SOURCE_CODE: ../codecov-browser-extension-${{ github.event.release.tag_name }}.tar.gz
      #     WEB_EXT_APPROVAL_TIMEOUT: 0 # Disable timeout for approval
