name: publish

permissions:
  id-token: write

on:
  release:
    types: [published]
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Generate source archive
        run: npm run archive
      - name: Install dependencies
        run: npm ci
      - name: Build extension
        run: npm run build
        env:
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - run: |
          jq --arg version "$VERSION" '.version=$version' dist/manifest.json > manifest.tmp.json \
            && mv manifest.tmp.json dist/manifest.json
          jq --arg version "$VERSION" '.version=$version' dist/manifest.firefox.json > manifest.tmp.json \
            && mv manifest.tmp.json dist/manifest.firefox.json
        env:
          # VERSION: ${{ github.event.release.tag_name }}
          VERSION: 0.5.7
      - run: |
          cp -r dist dist-firefox
          mv dist-firefox/manifest.firefox.json dist-firefox/manifest.json

      - run: cd dist-firefox && npx web-ext build

      - uses: actions/upload-artifact@v4
        with:
          name: codecov-0.5.7.zip
          path: ./dist-firefox/web-ext-artifacts/codecov-0.5.7.zip

      - uses: actions/upload-artifact@v4
        with:
          name: codecov-browser-extension.tar.gz
          path: codecov-browser-extension.tar.gz

      # - name: Publish to Chrome
      #   working-directory: dist
      #   run: npx chrome-webstore-upload-cli@2 upload --auto-publish
      #   env:
      #     EXTENSION_ID: "gedikamndpbemklijjkncpnolildpbgo"
      #     CLIENT_ID: ${{ secrets.GOOGLE_WEB_STORE_CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.GOOGLE_WEB_STORE_CLIENT_SECRET }}
      #     REFRESH_TOKEN: ${{ secrets.GOOGLE_WEB_STORE_REFRESH_TOKEN }}
      # - name: Publish to Firefox
      #   working-directory: dist-firefox
      #   run: npx web-ext sign
      #   env:
      #     WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_JWT_ISSUER }}
      #     WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_JWT_SECRET }}
      #     WEB_EXT_CHANNEL: listed
      #     WEB_EXT_API_UPLOAD_SOURCE_CODE: codecov-browser-extension.tar.gz
